ERROR 2024-07-05 13:53:10,640 log Internal Server Error: /api/announcement
Traceback (most recent call last):
  File "C:\Users\Guddu\Desktop\Django\NotificationService\env\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "C:\Users\Guddu\Desktop\Django\NotificationService\env\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Guddu\Desktop\Django\NotificationService\env\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "C:\Users\Guddu\Desktop\Django\NotificationService\env\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Guddu\Desktop\Django\NotificationService\env\Lib\site-packages\asgiref\sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Guddu\Desktop\Django\NotificationService\env\Lib\site-packages\asgiref\sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Guddu\Desktop\Django\NotificationService\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Guddu\Desktop\Django\NotificationService\env\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Guddu\Desktop\Django\NotificationService\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Guddu\Desktop\Django\NotificationService\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Guddu\Desktop\Django\NotificationService\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Guddu\Desktop\Django\NotificationService\env\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Guddu\Desktop\Django\NotificationService\NotificationModule\NotifyMe\views\views.py", line 300, in get
    objects = announcement_service.get_all_announcements()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AnnouncementService.get_all_announcements() missing 1 required positional argument: 'request'
ERROR 2024-07-05 13:53:10,648 runserver [35;1mHTTP GET /api/announcement 500 [0.50, 127.0.0.1:54121][0m
ERROR 2024-07-05 17:01:25,152 views Unexpected error occured while fetching. ERROR: NotifyMeException.handle_success() got an unexpected keyword argument 'status' 
ERROR 2024-07-05 17:01:25,157 log Internal Server Error: /api/announcement
ERROR 2024-07-05 17:01:25,159 runserver [35;1mHTTP GET /api/announcement 500 [0.32, 127.0.0.1:49307][0m
ERROR 2024-07-05 17:08:02,876 views Unexpected error occured while fetching. ERROR: NotifyMeException.handle_success() got an unexpected keyword argument 'status' 
ERROR 2024-07-05 17:08:02,880 log Internal Server Error: /api/announcement
ERROR 2024-07-05 17:08:02,881 runserver [35;1mHTTP GET /api/announcement 500 [0.05, 127.0.0.1:49682][0m
ERROR 2024-07-05 17:10:00,007 views Unexpected error occured while fetching. ERROR: NotifyMeException.handle_success() got an unexpected keyword argument 'status' 
ERROR 2024-07-05 17:10:00,017 log Internal Server Error: /api/announcement
ERROR 2024-07-05 17:10:00,018 runserver [35;1mHTTP GET /api/announcement 500 [0.05, 127.0.0.1:49734][0m
ERROR 2024-07-05 17:10:56,055 views Unexpected error occured while fetching. ERROR: NotifyMeException.handle_success() got an unexpected keyword argument 'status' 
ERROR 2024-07-05 17:10:56,125 log Internal Server Error: /api/announcement
ERROR 2024-07-05 17:10:56,126 runserver [35;1mHTTP GET /api/announcement 500 [0.09, 127.0.0.1:49767][0m
ERROR 2024-07-05 17:11:11,018 views Unexpected error occured while fetching. ERROR: NotifyMeException.handle_success() got an unexpected keyword argument 'status' 
ERROR 2024-07-05 17:11:11,021 log Internal Server Error: /api/announcement
ERROR 2024-07-05 17:11:11,022 runserver [35;1mHTTP GET /api/announcement 500 [0.07, 127.0.0.1:49777][0m
